name: run server

on:
  push:
    branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: run server
          run: |
                echo "run server"
                go run main.go &
                sleep 10
                go test -v